version = 1

[[annotations]]
path = "src/mosaico_ip_agent/*.py"
SPDX-FileCopyrightText = "2026 André S. Gomes"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/mosaico_ip_agent/config.py"
SPDX-FileCopyrightText = "2026 University of York"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    ".gitattributes",
    ".github/workflows/*.yml",
    ".gitignore",
    "CHANGELOG.md",
    "pyproject.toml",
    "README.md",
    "uv.lock",
    "Dockerfile"
]
SPDX-FileCopyrightText = "2026 André S. Gomes"
SPDX-License-Identifier = "MIT"
