name: Docker Build and Push

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  setup:
    name: Setup Metadata
    runs-on: ubuntu-latest
    outputs:
      python_version: ${{ steps.get-python-version.outputs.version }}
      clean_release_version: ${{ steps.get-release-version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get Python Version from Dockerfile
        id: get-python-version
        run: |
          PYTHON_FULL_VERSION=$(grep -oP 'FROM python:\K[0-9]+\.[0-9]+' Dockerfile | head -1)
          if [ -z "$PYTHON_FULL_VERSION" ]; then
            echo "::error::Could not extract Python version from Dockerfile."
            exit 1
          fi
          echo "version=${PYTHON_FULL_VERSION}" >> $GITHUB_OUTPUT

      - name: Get Clean Release Version
        id: get-release-version
        if: github.event_name == 'release'
        run: |
          CLEAN_RELEASE_VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          echo "version=${CLEAN_RELEASE_VERSION}" >> $GITHUB_OUTPUT

  build:
    name: Build and Push
    needs: setup
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write # Required by Docker Builder for signing and SLSA provenance
      packages: write # Required to push to GitHub Container Registry
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      meta-images: ghcr.io/${{ github.repository_owner }}/mosaico-ip-agent
      meta-tags: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=raw,value=python-${{ needs.setup.outputs.python_version }}
        type=semver,pattern={{version}}
        type=raw,value=${{ needs.setup.outputs.clean_release_version }}-python-${{ needs.setup.outputs.python_version }},enable=${{ github.event_name == 'release' }}
    secrets:
      # Authentication must be passed into the workflow securely
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
