name: PyPI Publish

on:
  release:
    types: [published]

jobs:
  publish-pypi:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Mandatory for Trusted Publishing (OIDC)
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        run: uv publish
